Vote bill
AfroDevGirl/congross pull request #8
Opened 2017-10-26 20:29 UTC by chelsea-shorte

Updated the Bills migration, added scaffolding for Amendments, code clean up for correctly spelling committee/subcommittee

2017-10-27 15:32 UTC, AfroDevGirl requested changes
Just need to remove some commented out lines in the migration. Once that's done i'll merge :)

2017-10-27 15:32 UTC, AfroDevGirl commented on db/migrate/20171021163620_create_bills.rb
> +      #serialize :actions
let's remove these comments

2017-10-27 21:07 UTC, chelsea-shorte commented
Ok! I've removed those comments.

2017-10-28 18:40 UTC, AfroDevGirl approved these changes

2017-10-28 18:40 UTC, merged